# Generated by Django 4.0 on 2022-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_users', '0003_patient_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
