# Generated by Django 4.0 on 2022-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_users', '0004_alter_patient_appointment_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='title',
            field=models.CharField(choices=[('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Oncologist', 'Oncologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Nephrologist', 'Nephrologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Neurologist', 'Neurologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Surgeon', 'Surgeon')], max_length=100, null=True),
        ),
    ]
