# Generated by Django 4.0 on 2022-04-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_users', '0005_patient_appointment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_appointment',
            old_name='title',
            new_name='Department',
        ),
    ]
